DROP TABLE IF EXISTS answers CASCADE;

CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  options_id INTEGER REFERENCES options(id) ON DELETE CASCADE
);
