DROP TABLE IF EXISTS choices CASCADE;

CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  user VARCHAR(255) NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  questions_id INTEGER REFERENCES questions(id) ON DELETE CASCADE
);
